name: build and push to dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_Docker:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.6.1
        
      - name: Build Docker image
        run: docker buildx build -t brachacorcos/dev-final-project .

      - name: login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_pass }}

      - name: push image to Docker Hub
        uses: docker/build-push-action@v6.7.0
        with:
          push: true
          tags: brachacorcos/dev-final-project